---
- name: Install ACL
  become: true
  apt:
    name: acl
    state: present
    update_cache: yes
    cache_valid_time: 86400

- name: Configure ACL on each path
  include_tasks: acl-item.yml
  with_items: "{{ server_writable_paths }}"
  loop_control:
    loop_var: acl_item
